---
  easy_rsa_dir: "/root/easy-rsa"
  ca_dir: "{{easy_rsa_dir}}/CA"
  openvpn_gzip : "https://github.com/OpenVPN/easy-rsa/releases/download/v{{easy_rsa_v}}/EasyRSA-{{easy_rsa_v}}.tgz"
  server_dir: "{{easy_rsa_dir}}/server"
  client_configs_dir: "/root/client-configs"
  keys_dir: "{{client_configs_dir}}/keys"

  easy_rsa_vars_country : US
  easy_rsa_vars_province : CA
  easy_rsa_vars_city : San Francisco
  easy_rsa_vars_org : ACME
  easy_rsa_vars_email : admin@acme.com
  easy_rsa_vars_ou : OU
