all:
  hosts:
    VPN:
      ansible_host: 10.0.1.24
      hostname: SeeSaw
      ansible_python_interpreter: /usr/bin/python3
  children:
    ubuntu:
      hosts:
        VPN:
      vars:
        easy_rsa_v : 3.2.1
        dns_server_1 : 10.0.1.11
        dns_server_2 : 10.0.1.11
        server_port: 2694
        remote_user : rabi
        update_command: sudo apt update
        upgrade_command: sudo apt upgrade
        cleanup_command: sudo apt autoremove
        ansible_user: rabi