- name: Update with latest packages
  apt: 
    update_cache : yes
- name: Upgrade the packages
  apt: 
    upgrade : yes
- name: Install a list of essential packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - bash-completion
      - wget 
      - curl 
      - ntp
      - ntpdate
      - git      
      - colordiff
      - dnsutils
      - screen
      - unzip
      - gzip
      - tar
      - htop
      - software-properties-common
      - python3-pip
      - python3-pexpect
      - python3-boto3
      - python3-boto
      - python3-jmespath
      - python3-packaging
      - python3-pexpect
      - python3-boto3
      - python3-boto
      - openvpn
      - tree

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Cleanup dependencies
  apt:
    autoclean: yes

- name: Set Timezone to America/New York
  become_user: root
  command: timedatectl set-timezone America/New_York

- name: Start NTP and enable
  service: name=ntp state=started enabled=yes