- name: Update with latest packages
  apt: 
    update_cache : yes
- name: Upgrade the packages
  apt: 
    upgrade : yes
- name: Install a list of essential packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - bash-completion 
      - wget 
      - curl 
      - ntp 
      - ntpdate 
      - git 
      - awscli 
      - colordiff
      - dnsutils
      - screen
      - unzip
      - gzip
      - tar
      - htop
      - software-properties-common
      - python3-pip
      - openvpn
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
- name: Cleanup dependencies
  apt:
    autoclean: yes
- name: install pexpect
  pip:
    name: pexpect
- name: install boto
  pip:
    name: boto
- name: install boto3
  pip:
    name: boto3
- name: Set Timezone to America/New York
  become_user: root
  command: timedatectl set-timezone America/New_York
- name: Ansible systemd start ntp
  systemd:
    name: ntp
    state: started