---
- name : Configure OpenVPN server on Ubuntu
  hosts : "{{ host }}"
  gather_facts: yes
  become: yes
  tasks: 
    - include_role:
        name: common
      vars:
    - include_role:
        name: server
      vars:
    - include_role:
        name: client
      vars: